version: "3"

services:
  postgres:
    image: postgres:11.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: G_3d7fW4K@wd*k3
      POSTGRES_DB: tcpa-dev
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
